arch: "amd64"

ingress:
  enabled: true
  hosts:
    - evergreen-ai-service.devprod-evergreen.staging.corp.mongodb.com
service:
  targetPort: 8080
mesh:
  enabled: true
  
services:
  - name: http
    ingress: true
    port: 80
    probes: true
    protocol: TCP
    targetPort: 8080
    type: ClusterIP

envSecrets:
  MONGO_URL: parsley-ai-secrets
  MONGO_USERNAME: parsley-ai-secrets
  MONGO_PASSWORD: parsley-ai-secrets
  OPENAI_KEY: parsley-ai-secrets