arch: "amd64"

ingress:
  enabled: true
  hosts:
    - parsley-ai-agent-devprod-evergreen.devprod-evergreen.staging.corp.mongodb.com
service:
  targetPort: 8080
mesh:
  enabled: true

envSecrets:
  MONGO_URL: parsley-ai-secrets
  MONGO_USERNAME: parsley-ai-secrets
  MONGO_PASSWORD: parsley-ai-secrets
  OPENAI_KEY: parsley-ai-secrets